### ISSUE TITLE
Install dotnet-script fail

### ISSUE THREAD

**Issue by anw194rb** [dotnet-script/dotnet-script#746]
Hi all,

I have a pipeline YAML that is attempting to install dotnet-script, but it fails.  My YAML for this is:

```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: 6.x

- task: DotNetCoreCLI@2
  displayName: 'Prepare Phrase SAAS'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update --global dotnet-script'
    includeNugetOrg: true
```

But I get the following error from Azure...
```

Tool 'dotnet-script' failed to update due to the following:
The tool package could not be restored.
Tool 'dotnet-script' failed to install. This failure may have been caused by: ...
```

I'm new to Azure pipelines, first time, so any help appreciated!

**Comment by filipw** [comment]
if it's an install, should you not be calling `dotnet tool install` instead of `update`?

**Comment by anw194rb** [comment]
Possibly, I'd read that 'update' will do both, but 'install' would fail if already present, so tried it out.  I also moved the nuget restore to before the script call and it gets past this (also added the ignore-failed-sources toggle).
```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6'
  inputs:
    version: '6.x'

- task: NuGetToolInstaller@1
   
- task: NuGetCommand@2
  displayName: 'Restore Packages'
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: NuGet.config
    includeNugetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Prepare Phrase SAAS'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-script --ignore-failed-sources'
```
Still get an issue later, when it gets to the actual build, but this change managed to fix my original problem.
