### ISSUE TITLE
❓Question: Executing `dotnet script` in AWS CodeBuild and fetching credentials for AWS service SDK clients

### ISSUE THREAD

**Issue by skirk-mpr** [dotnet-script/dotnet-script#774]
Hello!  Firstly, thanks so much for building this - dotnet script is amazing and I've started to convert a bunch of legacy helper scripts into my favorite language for safety and maintainability as a result!  While upon this journey, I just started converting some helper scripts that run in AWS CodeBuild to perform some actions that typically required a string of cryptic bash commands during our CI/CD pipelines.  

However, most recently the action that I am performing make use of the AWS SDKs for some service calls from the CI/CD pipeline (specifically AWS CodeBuild).  There is a default credential resolution chain that the SDKs follow when explicit credentials are not provided within the application code via the AWS service client construction.  

When running dotnet script to execute this script locally on my machine, the SDK successfully finds these credentials (for me in the .`aws/credentials file`) and the script execute successfully, able to interact with the AWS management plane.  However, when running AWS CodeBuild, where an IAM Role is associated with the compute/CodeBuild Project; these credentials are not resolved successfully.  Regular bash commands in the build spec, which utilize the AWS CLI, do successfully pick up the credentials for the IAM Role associated with this project).  

Was wondering if you had any thoughts about what might be preventing this with respect to how the scripts are executed. 
I've opened up a ticket with the AWS .NET SDK team for this issue (https://github.com/aws/aws-sdk-net/discussions/3724) but the person helping me out indicated that they are not super familiar with dotnet script so I figured I'd ask here :).

Thanks so much!

**Comment by filipw** [comment]
Thanks a lot.

dotnet-script does not provide any kind of isolation and should be able to access any environment variables from the host (in fact, this is what our own build script does, injects secrets as environment variables https://github.com/dotnet-script/dotnet-script/blob/master/.github/workflows/main.yml#L57-L62)

I am not really familiar with AWS toolchain, so it's hard for me to comment, but looking at the linked exception, it appears they have an order of precedence, where the SDK first looks at App.config (which will not be there), then at the local file (which you seem to have locally?) and then fallbacks to environment variables `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY` (which seem missing in your CI runs). 

I would start by making sure these variables are there and are populated (even using a CLI task, without anything .NET specific), since clearly without that, things won't work. This could be done for example by printing all of the available ones from a shell script, and then comparing to what csx script sees. If for some reason they are there before, but not once csx runs, you can try inheriting them explicitly, something like

```
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
dotnet script your-script.csx
```

I am not familiar with CodeBuild, but another option might be to try to pass these secret explicitly to the step (similar to the Github Actions link I posted above)?

**Comment by skirk-mpr** [comment]
AWS Support replied back with solution. So it looks like the environmental variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (and `AWS_SESSION_TOKEN`) are not prepopulated at runtime in CodeBuild with the credentials for the associated IAM Role. There is an additional explicit step need to retrieve those temporary credentials via a request to `AWS_CONTAINER_CREDENTIALS_FULL_URI` and then setting them.

Happy to confirm that doing exactly this allows the dotnet-script/CSX file to execute successfully, picking up the credential material from the environmental variables.

````
version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - curl -qL -o aws_credentials.json $AWS_CONTAINER_CREDENTIALS_FULL_URI > aws_credentials.json
      - export AWS_ACCESS_KEY_ID=$(cat aws_credentials.json | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(cat aws_credentials.json | jq -r '.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(cat aws_credentials.json | jq -r '.Token')
      - dotnet script LoadStepFunctionPayloads.csx $ENVIRONMENT workflow_payload_index.json
````
